[package]
name = "neovide"
version = "0.1.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"

[dependencies]
rust-embed="5.1.0"
ggez = "0.5"
derive-new = "0.5"
env_logger = "0.7.1"
neovim-lib = { git = "https://github.com/daa84/neovim-lib", version = "0.6" }
rmpv = "0.4.2"

[profile.release]
debug = true
